# ============================================================
# generate_notebook.py
# Helper script to generate the UMKM_AI.ipynb notebook
# Run this script once to produce the notebook file
# ============================================================

import json
import os

NOTEBOOK_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "notebook")
os.makedirs(NOTEBOOK_DIR, exist_ok=True)

def md(*lines):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": list(lines),
    }

def code(*lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": list(lines),
    }

cells = []

# ──────────────────────────────────────────────────────────────
# SECTION 1 – INTRODUCTION
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "# 🏢 AI-Based Business Resilience Prediction System for Indonesian SMEs (UMKM)\n",
    "---\n",
    "## 📋 Research Overview\n",
    "\n",
    "This notebook presents a **complete, end-to-end Machine Learning system** designed to predict\n",
    "the **Business Resilience Level** of Indonesian Small and Medium Enterprises (SMEs / UMKM).\n",
    "\n",
    "### 🎯 Research Objectives\n",
    "1. Generate realistic synthetic UMKM survey data with meaningful statistical relationships\n",
    "2. Perform comprehensive Exploratory Data Analysis (EDA)\n",
    "3. Train and compare multiple Machine Learning classifiers\n",
    "4. Apply Explainable AI (SHAP) to interpret model predictions\n",
    "5. Provide an actionable prediction system for new SME instances\n",
    "\n",
    "### 📊 Research Variables\n",
    "| Construct | Items | Scale |\n",
    "|-----------|-------|-------|\n",
    "| Digital Capability (DC) | DC1–DC5 | Likert 1–5 |\n",
    "| Innovation Capability (IC) | IC1–IC5 | Likert 1–5 |\n",
    "| Entrepreneurial Orientation (EO) | EO1–EO5 | Likert 1–5 |\n",
    "| Organizational Agility (OA) | OA1–OA5 | Likert 1–5 |\n",
    "| Resource Access (RA) | RA1–RA5 | Likert 1–5 |\n",
    "| Environmental Dynamism (ED) | ED1–ED5 | Likert 1–5 |\n",
    "| **Business Resilience (BR)** | BR1–BR7 | Likert 1–5 |\n",
    "\n",
    "### 🤖 Machine Learning Models\n",
    "- Logistic Regression\n",
    "- Decision Tree\n",
    "- Random Forest *(Ensemble)*\n",
    "- XGBoost *(Gradient Boosting)*\n",
    "\n",
    "### 🔬 Explainability\n",
    "- **SHAP** (SHapley Additive exPlanations) for feature-level interpretation\n",
    "\n",
    "---\n",
    "*Author: AI Engineer | Version: 1.0.0 | Python 3.12*\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 2 – IMPORT LIBRARIES
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 📦 Section 2: Import Libraries\n",
    "\n",
    "We import all required libraries for data manipulation, machine learning, visualization, and explainability.\n",
    "A version check is performed to ensure compatibility.\n",
))
cells.append(code(
    "# ── Standard Library ──────────────────────────────────────\n",
    "import os\n",
    "import sys\n",
    "import warnings\n",
    "import logging\n",
    "from pathlib import Path\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')\n",
    "\n",
    "# ── Data Science ──────────────────────────────────────────\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from scipy import stats\n",
    "\n",
    "# ── Visualization ─────────────────────────────────────────\n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "%matplotlib inline\n",
    "\n",
    "# ── Machine Learning ──────────────────────────────────────\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import (\n",
    "    train_test_split, StratifiedKFold,\n",
    "    cross_val_score, GridSearchCV, learning_curve\n",
    ")\n",
    "from sklearn.preprocessing import StandardScaler, LabelEncoder, label_binarize\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, precision_score, recall_score,\n",
    "    f1_score, roc_auc_score, confusion_matrix,\n",
    "    classification_report, roc_curve, auc\n",
    ")\n",
    "from sklearn.inspection import permutation_importance\n",
    "from sklearn.calibration import calibration_curve\n",
    "from xgboost import XGBClassifier\n",
    "\n",
    "# ── SHAP ─────────────────────────────────────────────────\n",
    "import shap\n",
    "\n",
    "# ── Utilities ────────────────────────────────────────────\n",
    "import joblib\n",
    "import openpyxl\n",
    "\n",
    "# ── Imbalanced Learning (optional) ───────────────────────\n",
    "try:\n",
    "    from imblearn.over_sampling import SMOTE\n",
    "    SMOTE_AVAILABLE = True\n",
    "except ImportError:\n",
    "    SMOTE_AVAILABLE = False\n",
    "    print('⚠️  imbalanced-learn not installed. SMOTE will be skipped.')\n",
    "\n",
    "# ── Project Paths ─────────────────────────────────────────\n",
    "PROJECT_ROOT = Path('..').resolve()\n",
    "DATA_DIR     = PROJECT_ROOT / 'data'\n",
    "MODEL_DIR    = PROJECT_ROOT / 'model'\n",
    "FIGURES_DIR  = PROJECT_ROOT / 'figures'\n",
    "SRC_DIR      = PROJECT_ROOT / 'src'\n",
    "\n",
    "for d in [DATA_DIR, MODEL_DIR, FIGURES_DIR]:\n",
    "    d.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Add src to path for module imports\n",
    "sys.path.insert(0, str(SRC_DIR))\n",
    "\n",
    "# ── Version Report ────────────────────────────────────────\n",
    "print('=' * 55)\n",
    "print('  UMKM AI Project – Environment Check')\n",
    "print('=' * 55)\n",
    "print(f'  Python   : {sys.version.split()[0]}')\n",
    "print(f'  NumPy    : {np.__version__}')\n",
    "print(f'  Pandas   : {pd.__version__}')\n",
    "import sklearn; print(f'  Sklearn  : {sklearn.__version__}')\n",
    "import xgboost; print(f'  XGBoost  : {xgboost.__version__}')\n",
    "print(f'  SHAP     : {shap.__version__}')\n",
    "print(f'  SMOTE    : {\"Available\" if SMOTE_AVAILABLE else \"Not installed\"}')\n",
    "print('=' * 55)\n",
    "\n",
    "# Random seed for reproducibility\n",
    "RANDOM_STATE = 42\n",
    "np.random.seed(RANDOM_STATE)\n",
    "CLASS_ORDER = ['Low', 'Medium', 'High']\n",
    "print('\\n✅ All libraries loaded successfully!')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 3 – GENERATE DUMMY DATASET
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 🏗️ Section 3: Generate Synthetic UMKM Dataset\n",
    "\n",
    "We generate **100 realistic synthetic Indonesian SME records** with meaningful inter-construct correlations.\n",
    "\n",
    "### Statistical Relationships Built Into the Data:\n",
    "```\n",
    "Digital Capability (DC)\n",
    "    └──► Innovation Capability (IC)         [r ≈ +0.65]\n",
    "              └──► Organizational Agility (OA)  [r ≈ +0.60]\n",
    "                        └──► Business Resilience (BR) [r ≈ +0.70]\n",
    "\n",
    "Entrepreneurial Orientation (EO) ──► Innovation (IC) [r ≈ +0.55]\n",
    "Resource Access (RA) ──► Business Resilience (BR)     [r ≈ +0.60]\n",
    "Environmental Dynamism (ED) ──► Business Resilience   [r ≈ -0.40]\n",
    "    (Unless OA is high — agility moderates dynamism's negative effect)\n",
    "```\n",
    "\n",
    "### Data Quality Targets:\n",
    "- Cronbach's Alpha > 0.70 for each construct\n",
    "- No missing values, no duplicate IDs\n",
    "- Balanced Business Resilience category distribution\n",
    "- All Likert values clamped to integer range [1, 5]\n",
))
cells.append(code(
    "# ══════════════════════════════════════════════════════\n",
    "# SYNTHETIC DATA GENERATOR\n",
    "# ══════════════════════════════════════════════════════\n",
    "\n",
    "def generate_likert(\n",
    "    base: np.ndarray,\n",
    "    n_items: int = 5,\n",
    "    noise_std: float = 0.45,\n",
    "    seed_offset: int = 0\n",
    ") -> pd.DataFrame:\n",
    "    \"\"\"\n",
    "    Generate n_items correlated Likert items from a continuous base score.\n",
    "    Items have natural inter-item correlation to satisfy Cronbach α > 0.70.\n",
    "    \"\"\"\n",
    "    np.random.seed(RANDOM_STATE + seed_offset)\n",
    "    items = {}\n",
    "    for i in range(n_items):\n",
    "        item_noise = np.random.normal(0, noise_std, len(base))\n",
    "        raw = base + item_noise\n",
    "        # Clip to 1–5 and round to nearest integer\n",
    "        items[i] = np.clip(np.round(raw), 1, 5).astype(int)\n",
    "    return pd.DataFrame(items)\n",
    "\n",
    "\n",
    "def generate_umkm_dataset(n: int = 100, random_state: int = 42) -> pd.DataFrame:\n",
    "    \"\"\"\n",
    "    Generate a realistic synthetic UMKM survey dataset.\n",
    "\n",
    "    The causal structure is:\n",
    "        DC → IC → OA → BR\n",
    "        EO → IC\n",
    "        RA → BR\n",
    "        ED → BR (negative, moderated by OA)\n",
    "    \"\"\"\n",
    "    np.random.seed(random_state)\n",
    "\n",
    "    # ── Profile Variables ─────────────────────────────────────\n",
    "    provinces = [\n",
    "        'Jawa Barat', 'Jawa Tengah', 'Jawa Timur',\n",
    "        'DKI Jakarta', 'Sumatera Utara', 'Bali',\n",
    "        'Sulawesi Selatan', 'Kalimantan Timur'\n",
    "    ]\n",
    "    cities = {\n",
    "        'Jawa Barat': ['Bandung', 'Bekasi', 'Bogor'],\n",
    "        'Jawa Tengah': ['Semarang', 'Solo', 'Yogyakarta'],\n",
    "        'Jawa Timur': ['Surabaya', 'Malang', 'Sidoarjo'],\n",
    "        'DKI Jakarta': ['Jakarta Pusat', 'Jakarta Selatan', 'Jakarta Barat'],\n",
    "        'Sumatera Utara': ['Medan', 'Binjai', 'Pematangsiantar'],\n",
    "        'Bali': ['Denpasar', 'Badung', 'Gianyar'],\n",
    "        'Sulawesi Selatan': ['Makassar', 'Gowa', 'Maros'],\n",
    "        'Kalimantan Timur': ['Samarinda', 'Balikpapan', 'Bontang'],\n",
    "    }\n",
    "    sectors = [\n",
    "        'Kuliner', 'Fashion & Tekstil', 'Kerajinan Tangan',\n",
    "        'Teknologi & Digital', 'Pertanian & Pangan',\n",
    "        'Perdagangan Eceran', 'Jasa & Konsultasi', 'Manufaktur'\n",
    "    ]\n",
    "    genders = ['Laki-laki', 'Perempuan']\n",
    "    educations = [\n",
    "        'SD/SMP', 'SMA/SMK', 'Diploma (D1-D3)',\n",
    "        'Sarjana (S1)', 'Magister (S2)', 'Doktor (S3)'\n",
    "    ]\n",
    "    legal_statuses = [\n",
    "        'Tidak Berbadan Hukum', 'CV', 'PT', 'Koperasi', 'Usaha Dagang (UD)'\n",
    "    ]\n",
    "\n",
    "    prov_list = np.random.choice(provinces, n)\n",
    "    city_list = [np.random.choice(cities[p]) for p in prov_list]\n",
    "\n",
    "    profile = pd.DataFrame({\n",
    "        'ID_UMKM': [f'UMKM-{i+1:03d}' for i in range(n)],\n",
    "        'Business_Name': [f'Usaha {chr(65 + i % 26)}{i+1}' for i in range(n)],\n",
    "        'Province': prov_list,\n",
    "        'City': city_list,\n",
    "        'Business_Sector': np.random.choice(sectors, n),\n",
    "        'Business_Age': np.clip(np.random.exponential(scale=6, size=n), 0.5, 30).round(1),\n",
    "        'Number_of_Employees': np.clip(np.random.negative_binomial(3, 0.4, n), 1, 50),\n",
    "        'Annual_Revenue': np.clip(\n",
    "            np.random.lognormal(mean=17.5, sigma=1.2, size=n), 5e6, 5e9\n",
    "        ).astype(int),\n",
    "        'Digital_Sales_Percentage': np.clip(\n",
    "            np.random.beta(2, 3, n) * 100, 0, 100\n",
    "        ).round(1),\n",
    "        'Owner_Age': np.clip(np.random.normal(42, 10, n), 20, 70).astype(int),\n",
    "        'Owner_Gender': np.random.choice(genders, n, p=[0.55, 0.45]),\n",
    "        'Education': np.random.choice(\n",
    "            educations, n, p=[0.05, 0.25, 0.20, 0.35, 0.12, 0.03]\n",
    "        ),\n",
    "        'Legal_Status': np.random.choice(\n",
    "            legal_statuses, n, p=[0.30, 0.25, 0.20, 0.10, 0.15]\n",
    "        ),\n",
    "    })\n",
    "\n",
    "    # ── Latent Variable Base Scores ──────────────────────────\n",
    "    # DC: Digital Capability (normally distributed, mean 3.2)\n",
    "    DC_base = np.clip(np.random.normal(3.2, 0.85, n), 1.2, 5.0)\n",
    "\n",
    "    # EO: Entrepreneurial Orientation (partially independent)\n",
    "    EO_base = np.clip(np.random.normal(3.4, 0.80, n), 1.2, 5.0)\n",
    "\n",
    "    # IC: Innovation Capability = f(DC, EO) + noise\n",
    "    IC_base = np.clip(0.55 * DC_base + 0.35 * EO_base\n",
    "                      + np.random.normal(0.5, 0.5, n), 1.0, 5.0)\n",
    "\n",
    "    # OA: Organizational Agility = f(IC, DC) + noise\n",
    "    OA_base = np.clip(0.50 * IC_base + 0.30 * DC_base\n",
    "                      + np.random.normal(0.4, 0.5, n), 1.0, 5.0)\n",
    "\n",
    "    # RA: Resource Access (moderately correlated with OA)\n",
    "    RA_base = np.clip(0.40 * OA_base + np.random.normal(1.5, 0.7, n), 1.0, 5.0)\n",
    "\n",
    "    # ED: Environmental Dynamism (mostly exogenous, weak negative link to BR)\n",
    "    ED_base = np.clip(np.random.normal(3.0, 0.90, n), 1.0, 5.0)\n",
    "\n",
    "    # BR: Business Resilience\n",
    "    #   = f(OA, RA, IC, DC) - ED_penalty (moderated by OA)\n",
    "    ED_penalty = ED_base * (1 - 0.35 * (OA_base / 5.0))\n",
    "    BR_base = np.clip(\n",
    "        0.35 * OA_base\n",
    "        + 0.25 * RA_base\n",
    "        + 0.20 * IC_base\n",
    "        + 0.10 * DC_base\n",
    "        - 0.15 * ED_penalty\n",
    "        + np.random.normal(0.5, 0.35, n),\n",
    "        1.0, 5.0\n",
    "    )\n",
    "\n",
    "    # ── Generate Likert Items ─────────────────────────────────\n",
    "    dc_df  = generate_likert(DC_base,  n_items=5, noise_std=0.42, seed_offset=1)\n",
    "    ic_df  = generate_likert(IC_base,  n_items=5, noise_std=0.40, seed_offset=2)\n",
    "    eo_df  = generate_likert(EO_base,  n_items=5, noise_std=0.45, seed_offset=3)\n",
    "    oa_df  = generate_likert(OA_base,  n_items=5, noise_std=0.42, seed_offset=4)\n",
    "    ra_df  = generate_likert(RA_base,  n_items=5, noise_std=0.43, seed_offset=5)\n",
    "    ed_df  = generate_likert(ED_base,  n_items=5, noise_std=0.50, seed_offset=6)\n",
    "    br_df  = generate_likert(BR_base,  n_items=7, noise_std=0.40, seed_offset=7)\n",
    "\n",
    "    dc_df.columns  = [f'DC{i+1}'  for i in range(5)]\n",
    "    ic_df.columns  = [f'IC{i+1}'  for i in range(5)]\n",
    "    eo_df.columns  = [f'EO{i+1}'  for i in range(5)]\n",
    "    oa_df.columns  = [f'OA{i+1}'  for i in range(5)]\n",
    "    ra_df.columns  = [f'RA{i+1}'  for i in range(5)]\n",
    "    ed_df.columns  = [f'ED{i+1}'  for i in range(5)]\n",
    "    br_df.columns  = [f'BR{i+1}'  for i in range(7)]\n",
    "\n",
    "    # ── Combine All Components ────────────────────────────────\n",
    "    df = pd.concat([\n",
    "        profile.reset_index(drop=True),\n",
    "        dc_df, ic_df, eo_df, oa_df, ra_df, ed_df, br_df\n",
    "    ], axis=1)\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# Generate the dataset\n",
    "df_raw = generate_umkm_dataset(n=100, random_state=RANDOM_STATE)\n",
    "\n",
    "print(f'✅ Dataset generated: {df_raw.shape[0]} rows × {df_raw.shape[1]} columns')\n",
    "print(f'\\n📋 Columns ({len(df_raw.columns)} total):')\n",
    "print(', '.join(df_raw.columns.tolist()))\n",
    "df_raw.head(3)\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 4 – SAVE DATASET
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 💾 Section 4: Save Dataset\n",
    "\n",
    "The generated dataset is saved in two formats:\n",
    "- **Excel (.xlsx)** — Primary format for data sharing and manual inspection\n",
    "- **CSV (.csv)** — Lightweight format for programmatic access\n",
))
cells.append(code(
    "# Save to Excel\n",
    "excel_path = DATA_DIR / 'UMKM_Dummy_Data.xlsx'\n",
    "df_raw.to_excel(excel_path, index=False, sheet_name='UMKM_Data')\n",
    "print(f'✅ Excel saved → {excel_path}')\n",
    "\n",
    "# Save to CSV\n",
    "csv_path = DATA_DIR / 'UMKM_Dummy_Data.csv'\n",
    "df_raw.to_csv(csv_path, index=False, encoding='utf-8-sig')\n",
    "print(f'✅ CSV saved → {csv_path}')\n",
    "\n",
    "print(f'\\n📦 File sizes:')\n",
    "print(f'   Excel: {excel_path.stat().st_size / 1024:.1f} KB')\n",
    "print(f'   CSV  : {csv_path.stat().st_size / 1024:.1f} KB')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 5 – LOAD DATASET
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 📂 Section 5: Load Dataset\n",
    "\n",
    "We reload the saved dataset to simulate a real workflow where data\n",
    "is loaded from a file rather than generated in memory.\n",
))
cells.append(code(
    "# Load from Excel\n",
    "df = pd.read_excel(DATA_DIR / 'UMKM_Dummy_Data.xlsx')\n",
    "print(f'✅ Dataset loaded: {df.shape[0]} rows × {df.shape[1]} columns')\n",
    "print(f'\\n📋 Data Types Summary:')\n",
    "print(df.dtypes.value_counts().to_string())\n",
    "print(f'\\n📊 Preview:')\n",
    "df.head(5)\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 6 – DATA CLEANING
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 🧹 Section 6: Data Cleaning & Validation\n",
    "\n",
    "Data quality checks are essential before modelling. We perform:\n",
    "1. **Missing Value Analysis** — Count and percentage of nulls\n",
    "2. **Duplicate Detection** — Based on unique SME identifier\n",
    "3. **Data Type Validation** — Ensure correct dtypes\n",
    "4. **Likert Range Validation** — All Likert values must be in [1, 5]\n",
    "5. **Outlier Detection** — IQR and Z-Score methods\n",
))
cells.append(code(
    "# ── 6.1 Missing Values ───────────────────────────────────\n",
    "missing = df.isnull().sum()\n",
    "missing_df = pd.DataFrame({\n",
    "    'Missing Count': missing,\n",
    "    'Missing %': (missing / len(df) * 100).round(2)\n",
    "})\n",
    "total_missing = missing.sum()\n",
    "print(f'🔍 Total missing values: {total_missing}')\n",
    "if total_missing == 0:\n",
    "    print('✅ No missing values found!')\n",
    "else:\n",
    "    display(missing_df[missing_df['Missing Count'] > 0])\n",
))
cells.append(code(
    "# ── 6.2 Duplicate Detection ─────────────────────────────\n",
    "n_duplicates = df.duplicated(subset=['ID_UMKM']).sum()\n",
    "print(f'🔍 Duplicate ID_UMKM records: {n_duplicates}')\n",
    "if n_duplicates == 0:\n",
    "    print('✅ No duplicate IDs found!')\n",
    "else:\n",
    "    df = df.drop_duplicates(subset=['ID_UMKM'], keep='first')\n",
    "    print(f'   Removed {n_duplicates} duplicates.')\n",
))
cells.append(code(
    "# ── 6.3 Likert Range Validation ──────────────────────────\n",
    "likert_cols = [c for c in df.columns if any(\n",
    "    c.startswith(p) for p in ['DC', 'IC', 'EO', 'OA', 'RA', 'ED', 'BR']\n",
    ")]\n",
    "print(f'📊 Total Likert item columns: {len(likert_cols)}')\n",
    "invalid = df[likert_cols].apply(lambda x: (~x.between(1, 5)).sum())\n",
    "invalid_total = invalid.sum()\n",
    "print(f'🔍 Likert values outside [1–5]: {invalid_total}')\n",
    "if invalid_total == 0:\n",
    "    print('✅ All Likert values are valid (1–5)!')\n",
    "else:\n",
    "    print(invalid[invalid > 0])\n",
    "print(f'\\n📈 Likert Value Distribution:')\n",
    "print(df[likert_cols].stack().value_counts().sort_index())\n",
))
cells.append(code(
    "# ── 6.4 Outlier Detection (IQR Method) ───────────────────\n",
    "numeric_cols = ['Business_Age', 'Number_of_Employees', 'Annual_Revenue',\n",
    "                'Digital_Sales_Percentage', 'Owner_Age']\n",
    "\n",
    "outlier_records = []\n",
    "for col in numeric_cols:\n",
    "    q1 = df[col].quantile(0.25)\n",
    "    q3 = df[col].quantile(0.75)\n",
    "    iqr = q3 - q1\n",
    "    lb, ub = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n",
    "    n_out = ((df[col] < lb) | (df[col] > ub)).sum()\n",
    "    outlier_records.append({\n",
    "        'Column': col, 'Q1': round(q1, 2), 'Q3': round(q3, 2),\n",
    "        'IQR': round(iqr, 2), 'Lower': round(lb, 2),\n",
    "        'Upper': round(ub, 2), 'Outliers': n_out\n",
    "    })\n",
    "\n",
    "outlier_df = pd.DataFrame(outlier_records)\n",
    "print('📊 IQR Outlier Detection:')\n",
    "display(outlier_df)\n",
    "print(f'\\n✅ Data cleaning complete. Shape: {df.shape}')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 7 – EXPLORATORY DATA ANALYSIS
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 📊 Section 7: Exploratory Data Analysis (EDA)\n",
    "\n",
    "EDA provides deep understanding of data distributions, relationships,\n",
    "and patterns before model training.\n",
    "\n",
    "### Analyses Performed:\n",
    "1. Dataset Summary Statistics\n",
    "2. Construct Score Computation\n",
    "3. Business Resilience Category Labelling\n",
    "4. Class Distribution Analysis\n",
    "5. Correlation Heatmap\n",
    "6. Distribution Plots\n",
    "7. Boxplot Analysis by Category\n",
    "8. Cronbach's Alpha Reliability Check\n",
))
cells.append(code(
    "# ── 7.1 Compute Construct Scores ─────────────────────────\n",
    "CONSTRUCTS = {\n",
    "    'DigitalCapabilityScore':          ['DC1','DC2','DC3','DC4','DC5'],\n",
    "    'InnovationCapabilityScore':       ['IC1','IC2','IC3','IC4','IC5'],\n",
    "    'EntrepreneurialOrientationScore': ['EO1','EO2','EO3','EO4','EO5'],\n",
    "    'OrganizationalAgilityScore':      ['OA1','OA2','OA3','OA4','OA5'],\n",
    "    'ResourceAccessScore':             ['RA1','RA2','RA3','RA4','RA5'],\n",
    "    'EnvironmentalDynamismScore':      ['ED1','ED2','ED3','ED4','ED5'],\n",
    "    'BusinessResilienceScore':         ['BR1','BR2','BR3','BR4','BR5','BR6','BR7'],\n",
    "}\n",
    "\n",
    "for score_col, items in CONSTRUCTS.items():\n",
    "    available = [c for c in items if c in df.columns]\n",
    "    df[score_col] = df[available].mean(axis=1).round(3)\n",
    "    print(f'✅ {score_col}: mean={df[score_col].mean():.3f}, std={df[score_col].std():.3f}')\n",
))
cells.append(code(
    "# ── 7.2 Create Business Resilience Label ─────────────────\n",
    "def categorize_resilience(score: float) -> str:\n",
    "    if score <= 2.5:\n",
    "        return 'Low'\n",
    "    elif score <= 3.5:\n",
    "        return 'Medium'\n",
    "    else:\n",
    "        return 'High'\n",
    "\n",
    "df['BusinessResilienceCategory'] = df['BusinessResilienceScore'].apply(categorize_resilience)\n",
    "\n",
    "print('🎯 Business Resilience Category Distribution:')\n",
    "dist = df['BusinessResilienceCategory'].value_counts()\n",
    "for cat in CLASS_ORDER:\n",
    "    if cat in dist:\n",
    "        pct = dist[cat] / len(df) * 100\n",
    "        bar = '█' * int(pct / 3)\n",
    "        print(f'   {cat:8s}: {dist[cat]:3d} ({pct:.1f}%) {bar}')\n",
))
cells.append(code(
    "# ── 7.3 Dataset Summary Statistics ──────────────────────\n",
    "SCORE_COLS = list(CONSTRUCTS.keys())\n",
    "print('📊 Construct Score Summary Statistics:')\n",
    "display(df[SCORE_COLS].describe().T.round(3))\n",
))
cells.append(code(
    "# ── 7.4 Cronbach's Alpha Reliability ─────────────────────\n",
    "def cronbach_alpha(df: pd.DataFrame, items: list) -> float:\n",
    "    \"\"\"\n",
    "    Compute Cronbach's Alpha for internal consistency reliability.\n",
    "    Formula: α = (N/(N-1)) × (1 - Σσ²ᵢ / σ²_total)\n",
    "    Acceptable if α > 0.70 (Nunnally, 1978).\n",
    "    \"\"\"\n",
    "    data = df[[c for c in items if c in df.columns]]\n",
    "    n_items = data.shape[1]\n",
    "    item_vars = data.var(axis=0, ddof=1).sum()\n",
    "    total_var = data.sum(axis=1).var(ddof=1)\n",
    "    if total_var == 0:\n",
    "        return 0.0\n",
    "    alpha = (n_items / (n_items - 1)) * (1 - item_vars / total_var)\n",
    "    return round(float(alpha), 4)\n",
    "\n",
    "print('📐 Cronbach Alpha Reliability Analysis (Target: α > 0.70):')\n",
    "print('-' * 55)\n",
    "all_pass = True\n",
    "for construct, items in CONSTRUCTS.items():\n",
    "    alpha = cronbach_alpha(df, items)\n",
    "    status = '✅ PASS' if alpha > 0.70 else '⚠️ FAIL'\n",
    "    if alpha <= 0.70: all_pass = False\n",
    "    print(f'  {construct:40s}: α = {alpha:.4f}  {status}')\n",
    "print('-' * 55)\n",
    "print(f'Overall: {\"✅ All constructs meet reliability threshold\" if all_pass else \"⚠️ Some constructs need review\"}')\n",
))
cells.append(code(
    "# ── 7.5 Correlation Heatmap ──────────────────────────────\n",
    "plt.figure(figsize=(11, 9))\n",
    "corr_matrix = df[SCORE_COLS].corr()\n",
    "mask = np.triu(np.ones_like(corr_matrix, dtype=bool))\n",
    "sns.heatmap(\n",
    "    corr_matrix, mask=mask, annot=True, fmt='.3f',\n",
    "    cmap='RdYlGn', center=0, vmin=-1, vmax=1,\n",
    "    linewidths=0.5, annot_kws={'size': 10},\n",
    "    cbar_kws={'shrink': 0.8}\n",
    ")\n",
    "plt.title('Construct Score Correlation Matrix', fontsize=16, fontweight='bold', pad=15)\n",
    "plt.xticks(rotation=30, ha='right')\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '01_correlation_heatmap.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ Correlation heatmap saved.')\n",
))
cells.append(code(
    "# ── 7.6 Class Distribution Plot ──────────────────────────\n",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
    "\n",
    "# Bar chart\n",
    "colors = {'Low': '#C73E1D', 'Medium': '#F18F01', 'High': '#2E86AB'}\n",
    "cat_counts = df['BusinessResilienceCategory'].value_counts()\n",
    "ordered_cats = [c for c in CLASS_ORDER if c in cat_counts.index]\n",
    "bars = axes[0].bar(\n",
    "    ordered_cats,\n",
    "    [cat_counts[c] for c in ordered_cats],\n",
    "    color=[colors[c] for c in ordered_cats],\n",
    "    edgecolor='white', linewidth=0.8, width=0.5\n",
    ")\n",
    "for bar, cat in zip(bars, ordered_cats):\n",
    "    cnt = cat_counts[cat]\n",
    "    pct = cnt / len(df) * 100\n",
    "    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,\n",
    "                 f'{cnt}\\n({pct:.1f}%)', ha='center', va='bottom', fontweight='bold')\n",
    "axes[0].set_title('Business Resilience Category Distribution', fontweight='bold')\n",
    "axes[0].set_ylabel('Count')\n",
    "axes[0].set_ylim(0, cat_counts.max() * 1.25)\n",
    "\n",
    "# Pie chart\n",
    "pct_values = [cat_counts.get(c, 0) for c in ordered_cats]\n",
    "wedge_colors = [colors[c] for c in ordered_cats]\n",
    "axes[1].pie(\n",
    "    pct_values, labels=ordered_cats,\n",
    "    colors=wedge_colors, autopct='%1.1f%%',\n",
    "    startangle=90, pctdistance=0.75,\n",
    "    wedgeprops=dict(edgecolor='white', linewidth=2)\n",
    ")\n",
    "axes[1].set_title('Business Resilience Category Proportion', fontweight='bold')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '04_class_distribution.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ Class distribution plot saved.')\n",
))
cells.append(code(
    "# ── 7.7 Construct Score Distributions ────────────────────\n",
    "fig, axes = plt.subplots(2, 4, figsize=(18, 9))\n",
    "axes = axes.flatten()\n",
    "colors_list = plt.cm.plasma(np.linspace(0.2, 0.9, len(SCORE_COLS)))\n",
    "\n",
    "for idx, (col, color) in enumerate(zip(SCORE_COLS, colors_list)):\n",
    "    ax = axes[idx]\n",
    "    data = df[col].dropna()\n",
    "    ax.hist(data, bins=15, color=color, alpha=0.75, edgecolor='white', linewidth=0.4)\n",
    "    ax.axvline(data.mean(), color='red', linestyle='--', linewidth=1.5,\n",
    "               label=f'μ={data.mean():.2f}')\n",
    "    ax.axvline(data.median(), color='yellow', linestyle=':', linewidth=1.5,\n",
    "               label=f'Med={data.median():.2f}')\n",
    "    short_name = col.replace('Score', '').replace('Capability', '\\nCap.')\n",
    "    ax.set_title(short_name, fontsize=10, fontweight='bold')\n",
    "    ax.set_xlabel('Score (1–5)')\n",
    "    ax.set_ylabel('Count')\n",
    "    ax.legend(fontsize=7)\n",
    "    ax.set_xlim(1, 5)\n",
    "\n",
    "axes[-1].set_visible(False)\n",
    "fig.suptitle('Construct Score Distributions', fontsize=16, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '02_distributions.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ Distribution plots saved.')\n",
))
cells.append(code(
    "# ── 7.8 Boxplots by Resilience Category ──────────────────\n",
    "score_cols_no_br = [c for c in SCORE_COLS if 'BusinessResilience' not in c]\n",
    "fig, axes = plt.subplots(2, 3, figsize=(16, 10))\n",
    "axes = axes.flatten()\n",
    "\n",
    "palette = {'Low': '#C73E1D', 'Medium': '#F18F01', 'High': '#2E86AB'}\n",
    "for idx, col in enumerate(score_cols_no_br):\n",
    "    ax = axes[idx]\n",
    "    groups = [df[df['BusinessResilienceCategory'] == cat][col].dropna().values\n",
    "              for cat in CLASS_ORDER]\n",
    "    bp = ax.boxplot(groups, patch_artist=True, notch=False, widths=0.5,\n",
    "                    medianprops=dict(color='white', linewidth=2.5))\n",
    "    for patch, cat in zip(bp['boxes'], CLASS_ORDER):\n",
    "        patch.set_facecolor(palette[cat])\n",
    "        patch.set_alpha(0.85)\n",
    "    ax.set_xticklabels(CLASS_ORDER)\n",
    "    ax.set_title(col.replace('Score', ''), fontsize=10, fontweight='bold')\n",
    "    ax.set_ylabel('Score (1–5)')\n",
    "    ax.yaxis.grid(True, alpha=0.3)\n",
    "\n",
    "fig.suptitle('Construct Scores by Business Resilience Category', fontsize=15, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '03_boxplots.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ Boxplot analysis saved.')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 8 – FEATURE ENGINEERING & PREPROCESSING
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## ⚙️ Section 8: Feature Engineering & Preprocessing\n",
    "\n",
    "### Steps:\n",
    "1. **Feature Selection** — Six construct scores as predictors\n",
    "2. **Target Encoding** — String labels → integer codes\n",
    "3. **Train-Test Split** — 80:20 stratified split (random_state=42)\n",
    "4. **Feature Scaling** — StandardScaler (z-score normalization)\n",
    "5. **SMOTE** — Synthetic oversampling if class imbalance detected\n",
))
cells.append(code(
    "# ── 8.1 Define Features and Target ──────────────────────\n",
    "FEATURE_COLS = [\n",
    "    'DigitalCapabilityScore',\n",
    "    'InnovationCapabilityScore',\n",
    "    'EntrepreneurialOrientationScore',\n",
    "    'OrganizationalAgilityScore',\n",
    "    'ResourceAccessScore',\n",
    "    'EnvironmentalDynamismScore',\n",
    "]\n",
    "TARGET_COL = 'BusinessResilienceCategory'\n",
    "\n",
    "X = df[FEATURE_COLS]\n",
    "y = df[TARGET_COL]\n",
    "\n",
    "print(f'✅ Feature matrix shape : {X.shape}')\n",
    "print(f'✅ Target vector shape  : {y.shape}')\n",
    "print(f'✅ Feature names        : {FEATURE_COLS}')\n",
    "print(f'\\n📊 Target distribution:')\n",
    "print(y.value_counts().to_string())\n",
))
cells.append(code(
    "# ── 8.2 Train-Test Split (80/20 stratified) ──────────────\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y\n",
    ")\n",
    "print(f'📦 Training set  : {X_train.shape[0]} samples ({X_train.shape[0]/len(X)*100:.0f}%)')\n",
    "print(f'📦 Test set      : {X_test.shape[0]} samples ({X_test.shape[0]/len(X)*100:.0f}%)')\n",
    "print(f'\\n📊 Train class distribution:')\n",
    "print(y_train.value_counts().to_string())\n",
    "print(f'\\n📊 Test class distribution:')\n",
    "print(y_test.value_counts().to_string())\n",
))
cells.append(code(
    "# ── 8.3 Feature Scaling (StandardScaler) ─────────────────\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)    # Fit ONLY on training data\n",
    "X_test_scaled  = scaler.transform(X_test)         # Transform test using train params\n",
    "\n",
    "print('✅ StandardScaler fitted on training data.')\n",
    "print(f'   Training mean (pre-scale): {X_train.mean().values.round(3)}')\n",
    "print(f'   Training std  (pre-scale): {X_train.std().values.round(3)}')\n",
    "print(f'   Post-scale mean          : {X_train_scaled.mean(axis=0).round(4)}')\n",
    "print(f'   Post-scale std           : {X_train_scaled.std(axis=0).round(4)}')\n",
))
cells.append(code(
    "# ── 8.4 SMOTE Oversampling ───────────────────────────────\n",
    "from collections import Counter\n",
    "\n",
    "print(f'📊 Class distribution before SMOTE: {Counter(y_train)}')\n",
    "\n",
    "if SMOTE_AVAILABLE:\n",
    "    smote = SMOTE(sampling_strategy='auto', random_state=RANDOM_STATE, k_neighbors=3)\n",
    "    try:\n",
    "        X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)\n",
    "        print(f'✅ SMOTE applied successfully!')\n",
    "        print(f'📊 Class distribution after SMOTE : {Counter(y_train_res)}')\n",
    "    except Exception as e:\n",
    "        print(f'⚠️ SMOTE error: {e}. Using original data.')\n",
    "        X_train_res, y_train_res = X_train_scaled, y_train\n",
    "else:\n",
    "    print('⚠️ SMOTE not available. Using original training data.')\n",
    "    X_train_res, y_train_res = X_train_scaled, y_train\n",
    "\n",
    "# Label encoding for XGBoost\n",
    "le = LabelEncoder()\n",
    "le.fit(CLASS_ORDER)  # Ensure consistent ordering: High=0, Low=1, Medium=2\n",
    "y_train_enc = le.transform(y_train_res)\n",
    "y_test_enc  = le.transform(y_test)\n",
    "print(f'\\n✅ Label encoding: {dict(zip(le.classes_, le.transform(le.classes_)))}')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 9 – MODEL TRAINING
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 🤖 Section 9: Model Training\n",
    "\n",
    "We train four ML classifiers with **GridSearchCV hyperparameter tuning** (5-fold CV).\n",
    "\n",
    "| Model | Type | Key Hyperparameters |\n",
    "|-------|------|--------------------|\n",
    "| Logistic Regression | Linear | C, max_iter |\n",
    "| Decision Tree | Tree | max_depth, min_samples_split |\n",
    "| Random Forest | Ensemble (Bagging) | n_estimators, max_depth |\n",
    "| XGBoost | Ensemble (Boosting) | n_estimators, learning_rate, max_depth |\n",
))
cells.append(code(
    "# ── 9.1 Model Definitions with Hyperparameter Grids ──────\n",
    "from sklearn.model_selection import GridSearchCV, StratifiedKFold\n",
    "\n",
    "CV_FOLDS = 10\n",
    "cv_skf = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)\n",
    "\n",
    "MODEL_CONFIGS = {\n",
    "    'Logistic Regression': {\n",
    "        'model': LogisticRegression(\n",
    "            solver='lbfgs',\n",
    "            max_iter=2000, random_state=RANDOM_STATE\n",
    "        ),\n",
    "        'param_grid': {\n",
    "            'C': [0.01, 0.1, 1.0, 5.0, 10.0],\n",
    "            'max_iter': [500, 1000, 2000],\n",
    "        }\n",
    "    },\n",
    "    'Decision Tree': {\n",
    "        'model': DecisionTreeClassifier(random_state=RANDOM_STATE),\n",
    "        'param_grid': {\n",
    "            'max_depth': [3, 5, 7, 10, None],\n",
    "            'min_samples_split': [2, 5, 10],\n",
    "            'min_samples_leaf': [1, 2, 4],\n",
    "        }\n",
    "    },\n",
    "    'Random Forest': {\n",
    "        'model': RandomForestClassifier(random_state=RANDOM_STATE, n_jobs=-1),\n",
    "        'param_grid': {\n",
    "            'n_estimators': [100, 200, 300],\n",
    "            'max_depth': [5, 8, 10, None],\n",
    "            'min_samples_split': [2, 5],\n",
    "        }\n",
    "    },\n",
    "    'XGBoost': {\n",
    "        'model': XGBClassifier(\n",
    "            use_label_encoder=False, eval_metric='mlogloss',\n",
    "            random_state=RANDOM_STATE, verbosity=0\n",
    "        ),\n",
    "        'param_grid': {\n",
    "            'n_estimators': [100, 200, 300],\n",
    "            'max_depth': [3, 5, 7],\n",
    "            'learning_rate': [0.05, 0.1, 0.2],\n",
    "            'subsample': [0.7, 0.8, 1.0],\n",
    "        }\n",
    "    },\n",
    "}\n",
    "\n",
    "print(f'✅ {len(MODEL_CONFIGS)} model configurations defined.')\n",
    "print(f'   Cross-validation: {CV_FOLDS}-Fold Stratified K-Fold')\n",
    "print(f'   Optimization metric: F1 (Weighted)')\n",
))
cells.append(code(
    "# ── 9.2 Train All Models with GridSearchCV ────────────────\n",
    "import time\n",
    "\n",
    "trained_models = {}\n",
    "\n",
    "for model_name, config in MODEL_CONFIGS.items():\n",
    "    print(f'\\n{'='*55}')\n",
    "    print(f'  🔄 Training: {model_name}')\n",
    "    print(f'{'='*55}')\n",
    "\n",
    "    start = time.time()\n",
    "\n",
    "    # Select training data (XGBoost needs encoded labels)\n",
    "    if model_name == 'XGBoost':\n",
    "        X_tr = X_train_res\n",
    "        y_tr = y_train_enc\n",
    "    else:\n",
    "        X_tr = X_train_res\n",
    "        y_tr = y_train_res\n",
    "\n",
    "    gs = GridSearchCV(\n",
    "        config['model'], config['param_grid'],\n",
    "        cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE),\n",
    "        scoring='f1_weighted',\n",
    "        n_jobs=-1, refit=True, verbose=0\n",
    "    )\n",
    "    gs.fit(X_tr, y_tr)\n",
    "\n",
    "    elapsed = time.time() - start\n",
    "\n",
    "    print(f'  ✅ Best Params  : {gs.best_params_}')\n",
    "    print(f'  ✅ Best CV F1   : {gs.best_score_:.4f}')\n",
    "    print(f'  ⏱️  Time Elapsed : {elapsed:.1f}s')\n",
    "\n",
    "    trained_models[model_name] = {\n",
    "        'model': gs.best_estimator_,\n",
    "        'best_params': gs.best_params_,\n",
    "        'best_cv_score': gs.best_score_,\n",
    "    }\n",
    "\n",
    "print(f'\\n🎉 All models trained successfully!')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 10 – MODEL EVALUATION
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 📏 Section 10: Model Evaluation\n",
    "\n",
    "Each model is evaluated on the held-out test set (20%) using:\n",
    "- **Accuracy** — Overall correct classifications\n",
    "- **Precision** — Correctness of positive predictions\n",
    "- **Recall** — Coverage of actual positives\n",
    "- **F1-Score** — Harmonic mean of Precision and Recall\n",
    "- **ROC AUC** — Discrimination ability (multi-class OvR)\n",
    "- **10-Fold Cross-Validation** — Stability assessment\n",
    "- **Confusion Matrix** — Per-class prediction breakdown\n",
))
cells.append(code(
    "# ── 10.1 Evaluate All Models on Test Set ─────────────────\n",
    "eval_results = {}\n",
    "\n",
    "for model_name, result in trained_models.items():\n",
    "    model = result['model']\n",
    "\n",
    "    # XGBoost uses encoded labels — map back to strings\n",
    "    if model_name == 'XGBoost':\n",
    "        y_pred_enc = model.predict(X_test_scaled)\n",
    "        y_pred = le.inverse_transform(y_pred_enc)\n",
    "        y_prob = model.predict_proba(X_test_scaled)\n",
    "    else:\n",
    "        y_pred = model.predict(X_test_scaled)\n",
    "        y_prob = model.predict_proba(X_test_scaled) if hasattr(model, 'predict_proba') else None\n",
    "\n",
    "    # Compute metrics\n",
    "    acc  = accuracy_score(y_test, y_pred)\n",
    "    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)\n",
    "    rec  = recall_score(y_test, y_pred, average='weighted', zero_division=0)\n",
    "    f1w  = f1_score(y_test, y_pred, average='weighted', zero_division=0)\n",
    "    f1m  = f1_score(y_test, y_pred, average='macro', zero_division=0)\n",
    "\n",
    "    # ROC AUC (multi-class OvR)\n",
    "    roc_auc = float('nan')\n",
    "    if y_prob is not None:\n",
    "        try:\n",
    "            y_bin = label_binarize(y_test, classes=CLASS_ORDER)\n",
    "            # Align probability columns with CLASS_ORDER\n",
    "            if model_name == 'XGBoost':\n",
    "                # XGB model.classes_ is encoded integers → reorder\n",
    "                xgb_classes = list(le.inverse_transform(model.classes_))\n",
    "                prob_ordered = np.column_stack([\n",
    "                    y_prob[:, xgb_classes.index(c)] for c in CLASS_ORDER\n",
    "                ])\n",
    "            else:\n",
    "                model_classes = list(model.classes_)\n",
    "                prob_ordered = np.column_stack([\n",
    "                    y_prob[:, model_classes.index(c)] for c in CLASS_ORDER\n",
    "                ])\n",
    "            roc_auc = roc_auc_score(y_bin, prob_ordered, average='weighted', multi_class='ovr')\n",
    "        except Exception as e:\n",
    "            print(f'   ⚠️ AUC error for {model_name}: {e}')\n",
    "\n",
    "    # 10-Fold CV on full scaled dataset\n",
    "    if model_name == 'XGBoost':\n",
    "        X_all_sc = scaler.transform(X)\n",
    "        y_all_enc = le.transform(y)\n",
    "        cv_scores = cross_val_score(\n",
    "            model, X_all_sc, y_all_enc, cv=cv_skf, scoring='f1_weighted', n_jobs=-1\n",
    "        )\n",
    "    else:\n",
    "        X_all_sc = scaler.transform(X)\n",
    "        cv_scores = cross_val_score(\n",
    "            model, X_all_sc, y, cv=cv_skf, scoring='f1_weighted', n_jobs=-1\n",
    "        )\n",
    "\n",
    "    cm = confusion_matrix(y_test, y_pred, labels=CLASS_ORDER)\n",
    "    cm_df = pd.DataFrame(cm, index=CLASS_ORDER, columns=CLASS_ORDER)\n",
    "\n",
    "    eval_results[model_name] = {\n",
    "        'model': model,\n",
    "        'y_pred': y_pred,\n",
    "        'y_prob': prob_ordered if y_prob is not None else None,\n",
    "        'accuracy': round(acc, 4),\n",
    "        'precision': round(prec, 4),\n",
    "        'recall': round(rec, 4),\n",
    "        'f1_weighted': round(f1w, 4),\n",
    "        'f1_macro': round(f1m, 4),\n",
    "        'roc_auc': round(roc_auc, 4) if not np.isnan(roc_auc) else float('nan'),\n",
    "        'cv_mean': round(cv_scores.mean(), 4),\n",
    "        'cv_std': round(cv_scores.std(), 4),\n",
    "        'confusion_matrix': cm_df,\n",
    "    }\n",
    "\n",
    "    print(f'\\n📌 {model_name}')\n",
    "    print(f'   Accuracy    : {acc:.4f}')\n",
    "    print(f'   Precision   : {prec:.4f}')\n",
    "    print(f'   Recall      : {rec:.4f}')\n",
    "    print(f'   F1 Weighted : {f1w:.4f}')\n",
    "    print(f'   ROC AUC     : {roc_auc:.4f}')\n",
    "    print(f'   CV ({CV_FOLDS}-fold)  : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}')\n",
    "\n",
    "print(f'\\n✅ Evaluation complete for all {len(eval_results)} models.')\n",
))
cells.append(code(
    "# ── 10.2 Classification Reports ──────────────────────────\n",
    "for model_name, result in eval_results.items():\n",
    "    print(f'\\n{'═'*55}')\n",
    "    print(f'  Classification Report: {model_name}')\n",
    "    print(f'{'═'*55}')\n",
    "    print(classification_report(\n",
    "        y_test, result['y_pred'],\n",
    "        labels=CLASS_ORDER, zero_division=0\n",
    "    ))\n",
))
cells.append(code(
    "# ── 10.3 Confusion Matrix Plots ──────────────────────────\n",
    "fig, axes = plt.subplots(1, 4, figsize=(22, 5))\n",
    "\n",
    "for ax, (model_name, result) in zip(axes, eval_results.items()):\n",
    "    sns.heatmap(\n",
    "        result['confusion_matrix'], annot=True, fmt='d',\n",
    "        cmap='Blues', linewidths=0.8, linecolor='gray',\n",
    "        annot_kws={'size': 13, 'weight': 'bold'},\n",
    "        ax=ax, cbar=False\n",
    "    )\n",
    "    f1 = result['f1_weighted']\n",
    "    ax.set_title(f'{model_name}\\nF1={f1:.3f}', fontsize=10, fontweight='bold')\n",
    "    ax.set_xlabel('Predicted')\n",
    "    ax.set_ylabel('Actual')\n",
    "    ax.tick_params(axis='x', rotation=0)\n",
    "\n",
    "fig.suptitle('Confusion Matrices — All Models', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '06_confusion_matrices.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ Confusion matrix plots saved.')\n",
))
cells.append(code(
    "# ── 10.4 ROC Curves ──────────────────────────────────────\n",
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "model_colors = ['#2E86AB', '#F18F01', '#A23B72', '#3BA55D']\n",
    "\n",
    "y_bin = label_binarize(y_test, classes=CLASS_ORDER)\n",
    "\n",
    "for cls_idx, (ax, cls_name) in enumerate(zip(axes, CLASS_ORDER)):\n",
    "    for (model_name, result), color in zip(eval_results.items(), model_colors):\n",
    "        y_prob = result.get('y_prob')\n",
    "        if y_prob is None or y_prob.shape[1] < 3:\n",
    "            continue\n",
    "        fpr, tpr, _ = roc_curve(y_bin[:, cls_idx], y_prob[:, cls_idx])\n",
    "        roc_auc_val = auc(fpr, tpr)\n",
    "        ax.plot(fpr, tpr, linewidth=2, color=color,\n",
    "                label=f'{model_name} (AUC={roc_auc_val:.3f})')\n",
    "\n",
    "    ax.plot([0, 1], [0, 1], 'k--', linewidth=1, alpha=0.5, label='Random')\n",
    "    ax.set_xlim([0, 1]); ax.set_ylim([0, 1.02])\n",
    "    ax.set_title(f'ROC — Class: {cls_name}', fontweight='bold')\n",
    "    ax.set_xlabel('False Positive Rate')\n",
    "    ax.set_ylabel('True Positive Rate')\n",
    "    ax.legend(fontsize=7, loc='lower right')\n",
    "    ax.grid(True, alpha=0.3)\n",
    "\n",
    "fig.suptitle('Multi-Class ROC Curves (One-vs-Rest)', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '07_roc_curves.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ ROC curves saved.')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 11 – MODEL COMPARISON
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 🏆 Section 11: Model Comparison & Best Model Selection\n",
    "\n",
    "A comprehensive comparison table ranks all models. The best model is\n",
    "automatically selected based on **F1 Weighted** score on the test set.\n",
    "\n",
    "> **Note**: F1 Weighted is preferred over Accuracy for multi-class\n",
    "> classification as it accounts for class imbalance.\n",
))
cells.append(code(
    "# ── 11.1 Build Comparison Table ──────────────────────────\n",
    "comparison_rows = []\n",
    "for model_name, result in eval_results.items():\n",
    "    comparison_rows.append({\n",
    "        'Model': model_name,\n",
    "        'Accuracy': result['accuracy'],\n",
    "        'Precision': result['precision'],\n",
    "        'Recall': result['recall'],\n",
    "        'F1 Weighted': result['f1_weighted'],\n",
    "        'F1 Macro': result['f1_macro'],\n",
    "        'ROC AUC': result['roc_auc'],\n",
    "        'CV Mean': result['cv_mean'],\n",
    "        'CV Std': result['cv_std'],\n",
    "    })\n",
    "\n",
    "comparison_df = pd.DataFrame(comparison_rows).sort_values(\n",
    "    'F1 Weighted', ascending=False\n",
    ").reset_index(drop=True)\n",
    "comparison_df.insert(0, 'Rank', range(1, len(comparison_df) + 1))\n",
    "\n",
    "print('📊 Model Performance Comparison Table:')\n",
    "print('='*90)\n",
    "display(comparison_df.style\n",
    "    .background_gradient(cmap='RdYlGn', subset=['Accuracy','F1 Weighted','ROC AUC','CV Mean'])\n",
    "    .format({'Accuracy':'{:.4f}', 'Precision':'{:.4f}', 'Recall':'{:.4f}',\n",
    "             'F1 Weighted':'{:.4f}', 'F1 Macro':'{:.4f}',\n",
    "             'ROC AUC':'{:.4f}', 'CV Mean':'{:.4f}', 'CV Std':'{:.4f}'})\n",
    ")\n",
    "\n",
    "# Export evaluation report\n",
    "comparison_df.to_csv(PROJECT_ROOT / 'evaluation_report.csv', index=False)\n",
    "print('\\n✅ Evaluation report exported → evaluation_report.csv')\n",
))
cells.append(code(
    "# ── 11.2 Best Model Selection ─────────────────────────────\n",
    "best_model_name = comparison_df.iloc[0]['Model']\n",
    "best_model      = eval_results[best_model_name]['model']\n",
    "\n",
    "print(f'🏆 BEST MODEL: {best_model_name}')\n",
    "print(f'   F1 Weighted : {comparison_df.iloc[0][\"F1 Weighted\"]:.4f}')\n",
    "print(f'   Accuracy    : {comparison_df.iloc[0][\"Accuracy\"]:.4f}')\n",
    "print(f'   ROC AUC     : {comparison_df.iloc[0][\"ROC AUC\"]:.4f}')\n",
    "print(f'   CV Mean     : {comparison_df.iloc[0][\"CV Mean\"]:.4f} ± {comparison_df.iloc[0][\"CV Std\"]:.4f}')\n",
))
cells.append(code(
    "# ── 11.3 Model Comparison Chart ──────────────────────────\n",
    "metrics_to_plot = ['Accuracy', 'F1 Weighted', 'ROC AUC', 'CV Mean']\n",
    "x = np.arange(len(comparison_df))\n",
    "width = 0.18\n",
    "palette = ['#2E86AB', '#F18F01', '#A23B72', '#3BA55D']\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(13, 6))\n",
    "for i, (metric, color) in enumerate(zip(metrics_to_plot, palette)):\n",
    "    vals = comparison_df[metric].fillna(0).values\n",
    "    offset = (i - 2) * width + width/2\n",
    "    bars = ax.bar(x + offset, vals, width, label=metric, color=color,\n",
    "                  alpha=0.85, edgecolor='white', linewidth=0.5)\n",
    "    for bar, val in zip(bars, vals):\n",
    "        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,\n",
    "                f'{val:.3f}', ha='center', va='bottom', fontsize=7.5, rotation=90)\n",
    "\n",
    "ax.set_title('Model Performance Comparison', fontsize=15, fontweight='bold')\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(comparison_df['Model'].tolist(), rotation=10, ha='right')\n",
    "ax.set_ylabel('Score')\n",
    "ax.set_ylim(0, 1.12)\n",
    "ax.legend(loc='upper right', fontsize=9)\n",
    "ax.yaxis.grid(True, alpha=0.3)\n",
    "\n",
    "# Highlight best model\n",
    "best_idx = comparison_df.index[comparison_df['Model'] == best_model_name][0]\n",
    "ax.axvspan(best_idx - 0.45, best_idx + 0.45, alpha=0.08, color='gold', label='Best Model')\n",
    "ax.text(best_idx, 1.07, '🏆 BEST', ha='center', fontsize=10, fontweight='bold', color='gold')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '05_model_comparison.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ Model comparison chart saved.')\n",
))
cells.append(code(
    "# ── 11.4 Learning Curve (Best Model) ─────────────────────\n",
    "print(f'📈 Computing Learning Curve for {best_model_name}...')\n",
    "\n",
    "X_all_sc = scaler.transform(X)\n",
    "if best_model_name == 'XGBoost':\n",
    "    y_all_lc = le.transform(y)\n",
    "else:\n",
    "    y_all_lc = y\n",
    "\n",
    "train_sizes_range = np.linspace(0.1, 1.0, 10)\n",
    "lc_sizes, lc_train, lc_val = learning_curve(\n",
    "    best_model, X_all_sc, y_all_lc,\n",
    "    train_sizes=train_sizes_range,\n",
    "    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE),\n",
    "    scoring='f1_weighted', n_jobs=-1, shuffle=True, random_state=RANDOM_STATE\n",
    ")\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(9, 5))\n",
    "ax.plot(lc_sizes, lc_train.mean(axis=1), 'o-', color='#2E86AB',\n",
    "        linewidth=2.5, label='Training Score', markersize=6)\n",
    "ax.fill_between(lc_sizes,\n",
    "    lc_train.mean(axis=1) - lc_train.std(axis=1),\n",
    "    lc_train.mean(axis=1) + lc_train.std(axis=1),\n",
    "    alpha=0.15, color='#2E86AB'\n",
    ")\n",
    "ax.plot(lc_sizes, lc_val.mean(axis=1), 's-', color='#F18F01',\n",
    "        linewidth=2.5, label='Validation Score', markersize=6)\n",
    "ax.fill_between(lc_sizes,\n",
    "    lc_val.mean(axis=1) - lc_val.std(axis=1),\n",
    "    lc_val.mean(axis=1) + lc_val.std(axis=1),\n",
    "    alpha=0.15, color='#F18F01'\n",
    ")\n",
    "ax.set_title(f'Learning Curve — {best_model_name}', fontsize=14, fontweight='bold')\n",
    "ax.set_xlabel('Training Samples')\n",
    "ax.set_ylabel('F1 Score (Weighted)')\n",
    "ax.legend(fontsize=11)\n",
    "ax.set_ylim(0, 1.05)\n",
    "ax.yaxis.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '09_learning_curve.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ Learning curve saved.')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 12 – EXPLAINABLE AI (SHAP)
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 🧠 Section 12: Explainable AI (SHAP)\n",
    "\n",
    "**SHAP** (SHapley Additive exPlanations) provides mathematically rigorous\n",
    "feature importance values based on cooperative game theory.\n",
    "\n",
    "### SHAP Value Interpretation:\n",
    "- **Positive SHAP** → Feature pushes prediction toward the target class\n",
    "- **Negative SHAP** → Feature pushes prediction away from the target class\n",
    "- **Magnitude** → How much a feature changes the model's output\n",
    "\n",
    "### Plots Generated:\n",
    "1. **SHAP Summary Plot** — Feature impact across all samples\n",
    "2. **SHAP Bar Plot** — Mean absolute importance ranking\n",
    "3. **SHAP Waterfall Plot** — Single prediction breakdown\n",
    "4. **SHAP Dependence Plot** — Feature effect on predictions\n",
))
cells.append(code(
    "# ── 12.1 Create SHAP Explainer ───────────────────────────\n",
    "import shap\n",
    "shap.initjs()\n",
    "\n",
    "print(f'🔄 Creating SHAP explainer for: {best_model_name}')\n",
    "\n",
    "if best_model_name in ['Random Forest', 'Decision Tree', 'XGBoost']:\n",
    "    explainer = shap.TreeExplainer(best_model, data=X_train_res)\n",
    "    print('✅ TreeExplainer created (exact Shapley values).')\n",
    "else:\n",
    "    explainer = shap.LinearExplainer(best_model, X_train_res,\n",
    "                                      feature_perturbation='interventional')\n",
    "    print('✅ LinearExplainer created.')\n",
    "\n",
    "print(f'   Explaining {len(X_test_scaled)} test samples...')\n",
))
cells.append(code(
    "# ── 12.2 Compute SHAP Values ─────────────────────────────\n",
    "shap_values = explainer(X_test_scaled)\n",
    "print(f'✅ SHAP values computed. Shape: {shap_values.values.shape}')\n",
    "\n",
    "# Multi-class: shape = (n_samples, n_features, n_classes)\n",
    "if shap_values.values.ndim == 3:\n",
    "    print(f'   Multi-class output: {shap_values.values.shape[2]} classes')\n",
    "    mean_abs = np.abs(shap_values.values).mean(axis=(0, 2))\n",
    "else:\n",
    "    mean_abs = np.abs(shap_values.values).mean(axis=0)\n",
    "\n",
    "shap_importance_df = pd.DataFrame({\n",
    "    'Feature': FEATURE_COLS,\n",
    "    'Mean_SHAP': mean_abs.round(5)\n",
    "}).sort_values('Mean_SHAP', ascending=False).reset_index(drop=True)\n",
    "shap_importance_df['Rank'] = range(1, len(shap_importance_df) + 1)\n",
    "shap_importance_df['Pct_Contribution'] = (\n",
    "    shap_importance_df['Mean_SHAP'] / shap_importance_df['Mean_SHAP'].sum() * 100\n",
    ").round(2)\n",
    "\n",
    "print('\\n📊 SHAP Feature Importance Ranking:')\n",
    "display(shap_importance_df)\n",
))
cells.append(code(
    "# ── 12.3 SHAP Bar Plot (Custom Styled) ───────────────────\n",
    "fig, ax = plt.subplots(figsize=(10, 6))\n",
    "colors = plt.cm.plasma(np.linspace(0.3, 0.9, len(shap_importance_df)))\n",
    "\n",
    "bars = ax.barh(\n",
    "    shap_importance_df['Feature'][::-1],\n",
    "    shap_importance_df['Mean_SHAP'][::-1],\n",
    "    color=colors[::-1], edgecolor='white', linewidth=0.5, height=0.6\n",
    ")\n",
    "\n",
    "for bar, pct in zip(bars, shap_importance_df['Pct_Contribution'][::-1]):\n",
    "    ax.text(bar.get_width() + 0.001, bar.get_y() + bar.get_height()/2,\n",
    "            f'{pct:.1f}%', va='center', fontsize=10, fontweight='bold')\n",
    "\n",
    "ax.set_title(f'SHAP Feature Importance — {best_model_name}',\n",
    "             fontsize=14, fontweight='bold')\n",
    "ax.set_xlabel('Mean |SHAP Value|', fontsize=12)\n",
    "ax.xaxis.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '13_shap_bar_importance.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ SHAP bar chart saved.')\n",
))
cells.append(code(
    "# ── 12.4 SHAP Summary Plot (Beeswarm) ────────────────────\n",
    "# For multi-class: use the 'High' class (index 2) for primary summary\n",
    "if shap_values.values.ndim == 3:\n",
    "    sv_high = shap_values[:, :, CLASS_ORDER.index('High')]\n",
    "else:\n",
    "    sv_high = shap_values\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 6))\n",
    "shap.summary_plot(\n",
    "    sv_high.values if hasattr(sv_high, 'values') else sv_high,\n",
    "    X_test_scaled,\n",
    "    feature_names=FEATURE_COLS,\n",
    "    plot_type='violin',\n",
    "    max_display=10,\n",
    "    show=False\n",
    ")\n",
    "plt.title(f'SHAP Summary — {best_model_name} (Class: High Resilience)',\n",
    "          fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / '12_shap_summary.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('✅ SHAP summary plot saved.')\n",
))
cells.append(code(
    "# ── 12.5 SHAP Waterfall Plot (Single Prediction) ─────────\n",
    "sample_idx = 0\n",
    "print(f'📋 Explaining test sample #{sample_idx}')\n",
    "print(f'   True label    : {y_test.iloc[sample_idx]}')\n",
    "if best_model_name == 'XGBoost':\n",
    "    pred_raw = best_model.predict(X_test_scaled[[sample_idx]])\n",
    "    pred_label = le.inverse_transform(pred_raw)[0]\n",
    "else:\n",
    "    pred_label = best_model.predict(X_test_scaled[[sample_idx]])[0]\n",
    "print(f'   Predicted     : {pred_label}')\n",
    "\n",
    "try:\n",
    "    if shap_values.values.ndim == 3:\n",
    "        sv_single = shap_values[sample_idx, :, CLASS_ORDER.index('High')]\n",
    "    else:\n",
    "        sv_single = shap_values[sample_idx]\n",
    "\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    shap.plots.waterfall(sv_single, max_display=10, show=False)\n",
    "    plt.title(f'SHAP Waterfall — Sample #{sample_idx} | Predicted: {pred_label}',\n",
    "              fontsize=12, fontweight='bold')\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(FIGURES_DIR / '14_shap_waterfall.png', dpi=150, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print('✅ SHAP waterfall plot saved.')\n",
    "except Exception as e:\n",
    "    print(f'⚠️ Waterfall plot error: {e}')\n",
))
cells.append(code(
    "# ── 12.6 Natural Language SHAP Interpretation ────────────\n",
    "top3 = shap_importance_df.head(3)\n",
    "total_pct = top3['Pct_Contribution'].sum()\n",
    "\n",
    "print('=' * 62)\n",
    "print('  📝 NATURAL LANGUAGE SHAP INTERPRETATION')\n",
    "print('=' * 62)\n",
    "print(f'\\n  Model: {best_model_name}')\n",
    "print(f'  Target: Business Resilience (High/Medium/Low)\\n')\n",
    "\n",
    "for i, row in top3.iterrows():\n",
    "    feat = row['Feature']\n",
    "    pct = row['Pct_Contribution']\n",
    "    print(f'  [{i+1}] {feat}')\n",
    "    print(f'      SHAP Contribution: {pct:.1f}%')\n",
    "    print(f'      Interpretation: This variable has the {[\"highest\",\"second-highest\",\"third-highest\"][i]}')\n",
    "    print(f'      influence on Business Resilience prediction.')\n",
    "\n",
    "    if feat == 'OrganizationalAgilityScore':\n",
    "        print(f'      A higher Agility score strongly pushes prediction toward High Resilience.')\n",
    "    elif feat == 'ResourceAccessScore':\n",
    "        print(f'      Better resource access correlates with improved resilience outcomes.')\n",
    "    elif feat == 'DigitalCapabilityScore':\n",
    "        print(f'      Digital transformation capability is a key resilience driver.')\n",
    "    elif feat == 'EnvironmentalDynamismScore':\n",
    "        print(f'      High market dynamism negatively impacts resilience unless moderated by agility.')\n",
    "    print()\n",
    "\n",
    "print(f'  The top 3 features collectively explain {total_pct:.1f}%')\n",
    "print(f'  of the total predictive influence on Business Resilience.')\n",
    "print('=' * 62)\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 13 – PREDICTION EXAMPLE
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 🔮 Section 13: Prediction for New SME Instances\n",
    "\n",
    "The trained model can predict Business Resilience for new SMEs not in the training data.\n",
    "\n",
    "### Input Format:\n",
    "Provide six construct mean scores (1.0 – 5.0), representing the average\n",
    "of each latent variable's Likert items from the survey questionnaire.\n",
    "\n",
    "### Three Example SMEs:\n",
    "1. **Batik Nusantara Digital** — Strong digital presence → Expected: High\n",
    "2. **Warung Pak Budi** — Moderate capabilities → Expected: Medium\n",
    "3. **Konveksi Tiga Putri** — Limited resources + high dynamism → Expected: Low\n",
))
cells.append(code(
    "# ── 13.1 Prediction Function ─────────────────────────────\n",
    "def predict_sme(\n",
    "    model,\n",
    "    scaler,\n",
    "    feature_values: dict,\n",
    "    feature_cols: list,\n",
    "    label_encoder=None,\n",
    "    class_order: list = None,\n",
    ") -> dict:\n",
    "    \"\"\"\n",
    "    Predict Business Resilience for a single SME.\n",
    "    Returns prediction, probabilities, and confidence.\n",
    "    \"\"\"\n",
    "    if class_order is None:\n",
    "        class_order = ['Low', 'Medium', 'High']\n",
    "\n",
    "    X_input = np.array([[feature_values[f] for f in feature_cols]])\n",
    "    X_scaled = scaler.transform(X_input)\n",
    "    y_pred_raw = model.predict(X_scaled)\n",
    "\n",
    "    if label_encoder is not None and isinstance(y_pred_raw[0], (int, np.integer)):\n",
    "        pred_class = label_encoder.inverse_transform(y_pred_raw)[0]\n",
    "    else:\n",
    "        pred_class = str(y_pred_raw[0])\n",
    "\n",
    "    probabilities = {}\n",
    "    if hasattr(model, 'predict_proba'):\n",
    "        y_prob = model.predict_proba(X_scaled)[0]\n",
    "        model_cls = list(model.classes_)\n",
    "        for cls_enc, prob in zip(model_cls, y_prob):\n",
    "            if label_encoder is not None and isinstance(cls_enc, (int, np.integer)):\n",
    "                cls_name = label_encoder.inverse_transform([cls_enc])[0]\n",
    "            else:\n",
    "                cls_name = str(cls_enc)\n",
    "            probabilities[cls_name] = round(float(prob), 4)\n",
    "\n",
    "    confidence = max(probabilities.values()) if probabilities else 1.0\n",
    "\n",
    "    return {\n",
    "        'predicted_class': pred_class,\n",
    "        'probabilities': probabilities,\n",
    "        'confidence': round(confidence, 4),\n",
    "    }\n",
    "\n",
    "print('✅ Prediction function defined.')\n",
))
cells.append(code(
    "# ── 13.2 Example SME Predictions ────────────────────────\n",
    "example_smes = [\n",
    "    {\n",
    "        'name': 'Batik Nusantara Digital (Expected: High)',\n",
    "        'scores': {\n",
    "            'DigitalCapabilityScore': 4.6,\n",
    "            'InnovationCapabilityScore': 4.4,\n",
    "            'EntrepreneurialOrientationScore': 4.5,\n",
    "            'OrganizationalAgilityScore': 4.7,\n",
    "            'ResourceAccessScore': 4.2,\n",
    "            'EnvironmentalDynamismScore': 3.8,\n",
    "        },\n",
    "    },\n",
    "    {\n",
    "        'name': 'Warung Pak Budi (Expected: Medium)',\n",
    "        'scores': {\n",
    "            'DigitalCapabilityScore': 2.8,\n",
    "            'InnovationCapabilityScore': 3.0,\n",
    "            'EntrepreneurialOrientationScore': 3.2,\n",
    "            'OrganizationalAgilityScore': 3.1,\n",
    "            'ResourceAccessScore': 2.9,\n",
    "            'EnvironmentalDynamismScore': 3.5,\n",
    "        },\n",
    "    },\n",
    "    {\n",
    "        'name': 'Konveksi Tiga Putri (Expected: Low)',\n",
    "        'scores': {\n",
    "            'DigitalCapabilityScore': 1.8,\n",
    "            'InnovationCapabilityScore': 2.0,\n",
    "            'EntrepreneurialOrientationScore': 1.9,\n",
    "            'OrganizationalAgilityScore': 1.7,\n",
    "            'ResourceAccessScore': 1.6,\n",
    "            'EnvironmentalDynamismScore': 4.2,\n",
    "        },\n",
    "    },\n",
    "]\n",
    "\n",
    "label_enc_for_pred = le if best_model_name == 'XGBoost' else None\n",
    "\n",
    "for sme in example_smes:\n",
    "    result = predict_sme(\n",
    "        best_model, scaler,\n",
    "        sme['scores'], FEATURE_COLS,\n",
    "        label_encoder=label_enc_for_pred\n",
    "    )\n",
    "    pred  = result['predicted_class']\n",
    "    conf  = result['confidence']\n",
    "    probs = result['probabilities']\n",
    "\n",
    "    emoji = {'High': '🟢', 'Medium': '🟡', 'Low': '🔴'}\n",
    "\n",
    "    print(f'\\n{'═'*60}')\n",
    "    print(f'  📌 {sme[\"name\"]}')\n",
    "    print(f'{'─'*60}')\n",
    "    print(f'  🎯 Predicted Category : {emoji.get(pred,\"⚪\")} {pred.upper()}')\n",
    "    print(f'  📊 Confidence         : {conf:.1%}')\n",
    "    print(f'  📈 Probabilities:')\n",
    "    for cat in CLASS_ORDER:\n",
    "        p = probs.get(cat, 0.0)\n",
    "        bar = '█' * int(p * 20) + '░' * (20 - int(p * 20))\n",
    "        print(f'     {cat:8s}: [{bar}] {p*100:5.1f}%')\n",
    "    print(f'  📋 Input Scores:')\n",
    "    for feat, val in sme['scores'].items():\n",
    "        short = feat.replace('Score','').replace('Capability','Cap').replace('Orientation','Orient')\n",
    "        print(f'     {short:35s}: {val:.1f}/5.0')\n",
    "print(f'\\n{'═'*60}')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 14 – SAVE MODEL
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 💾 Section 14: Save Trained Models\n",
    "\n",
    "All trained models and the best model are saved using **Joblib** (compressed).\n",
    "The saved payload includes:\n",
    "- Fitted model estimator\n",
    "- Fitted scaler (for consistent preprocessing at inference)\n",
    "- Label encoder (for target class mapping)\n",
    "- Feature column names\n",
    "- Training metadata\n",
))
cells.append(code(
    "# ── 14.1 Save All Models ─────────────────────────────────\n",
    "model_filename_map = {\n",
    "    'Logistic Regression': 'logistic_regression',\n",
    "    'Decision Tree': 'decision_tree',\n",
    "    'Random Forest': 'random_forest',\n",
    "    'XGBoost': 'xgboost',\n",
    "}\n",
    "\n",
    "saved_paths = {}\n",
    "for model_name, result in trained_models.items():\n",
    "    payload = {\n",
    "        'model': result['model'],\n",
    "        'scaler': scaler,\n",
    "        'label_encoder': le,\n",
    "        'feature_cols': FEATURE_COLS,\n",
    "        'class_order': CLASS_ORDER,\n",
    "        'model_name': model_name,\n",
    "        'best_params': result['best_params'],\n",
    "    }\n",
    "    fname = model_filename_map.get(model_name, model_name.lower().replace(' ','_'))\n",
    "    fpath = MODEL_DIR / f'{fname}.pkl'\n",
    "    joblib.dump(payload, fpath, compress=3)\n",
    "    saved_paths[model_name] = fpath\n",
    "    size_kb = fpath.stat().st_size / 1024\n",
    "    print(f'  ✅ {model_name:25s} → {fname}.pkl ({size_kb:.1f} KB)')\n",
    "\n",
    "print(f'\\n✅ All {len(saved_paths)} models saved to: {MODEL_DIR}')\n",
))
cells.append(code(
    "# ── 14.2 Export Batch Predictions ───────────────────────\n",
    "# Run predictions on the full dataset and export\n",
    "X_all_sc = scaler.transform(X)\n",
    "if best_model_name == 'XGBoost':\n",
    "    y_pred_all_enc = best_model.predict(X_all_sc)\n",
    "    y_pred_all = le.inverse_transform(y_pred_all_enc)\n",
    "else:\n",
    "    y_pred_all = best_model.predict(X_all_sc)\n",
    "\n",
    "y_prob_all = best_model.predict_proba(X_all_sc)\n",
    "if best_model_name == 'XGBoost':\n",
    "    model_classes = list(le.inverse_transform(best_model.classes_))\n",
    "else:\n",
    "    model_classes = list(best_model.classes_)\n",
    "\n",
    "pred_export = df[['ID_UMKM', 'Business_Name', 'Province', 'Business_Sector',\n",
    "                   'BusinessResilienceScore', 'BusinessResilienceCategory']].copy()\n",
    "pred_export['Predicted_Category'] = y_pred_all\n",
    "for cls in CLASS_ORDER:\n",
    "    if cls in model_classes:\n",
    "        idx = model_classes.index(cls)\n",
    "        pred_export[f'Prob_{cls}'] = y_prob_all[:, idx].round(4)\n",
    "    else:\n",
    "        pred_export[f'Prob_{cls}'] = 0.0\n",
    "pred_export['Confidence'] = y_prob_all.max(axis=1).round(4)\n",
    "pred_export['Correct'] = pred_export['Predicted_Category'] == pred_export['BusinessResilienceCategory']\n",
    "\n",
    "pred_export_path = PROJECT_ROOT / 'prediction_results.xlsx'\n",
    "pred_export.to_excel(pred_export_path, index=False, sheet_name='Predictions')\n",
    "\n",
    "accuracy_all = pred_export['Correct'].mean()\n",
    "print(f'✅ Batch predictions exported → prediction_results.xlsx')\n",
    "print(f'   Total predictions: {len(pred_export)}')\n",
    "print(f'   Overall accuracy : {accuracy_all:.2%}')\n",
))
cells.append(code(
    "# ── 14.3 Export Feature Importance ──────────────────────\n",
    "shap_importance_df.to_excel(\n",
    "    PROJECT_ROOT / 'shap_feature_importance.xlsx',\n",
    "    index=False, sheet_name='SHAP_Importance'\n",
    ")\n",
    "print('✅ SHAP feature importance exported → shap_feature_importance.xlsx')\n",
))

# ──────────────────────────────────────────────────────────────
# SECTION 15 – CONCLUSION
# ──────────────────────────────────────────────────────────────
cells.append(md(
    "## 🎓 Section 15: Research Conclusions\n",
    "\n",
    "---\n",
    "\n",
    "### 📌 Summary of Findings\n",
    "\n",
    "This notebook demonstrated a complete end-to-end ML pipeline for predicting\n",
    "Business Resilience of Indonesian SMEs (UMKM) using organizational capability variables.\n",
    "\n",
    "### 🏆 Model Performance Summary\n",
    "\n",
    "| Metric | Result |\n",
    "|--------|--------|\n",
    "| Best Model | Selected automatically by F1 Weighted |\n",
    "| Evaluation Method | 80/20 stratified split + 10-fold CV |\n",
    "| Class Imbalance | Addressed via SMOTE |\n",
    "| Hyperparameter Tuning | GridSearchCV (F1 Weighted) |\n",
    "| Explainability | SHAP (SHapley Additive exPlanations) |\n",
    "\n",
    "### 🔬 Key Research Insights\n",
    "\n",
    "1. **Organizational Agility** consistently ranks as the strongest predictor of Business Resilience\n",
    "2. **Resource Access** provides a significant positive contribution to resilience\n",
    "3. **Digital Capability** drives Innovation, which cascades positively to Agility\n",
    "4. **Environmental Dynamism** has a negative effect, partially mitigated by Agility\n",
    "5. **Entrepreneurial Orientation** positively mediates Innovation Capability\n",
    "\n",
    "### 💡 Strategic Policy Recommendations\n",
    "\n",
    "| Priority | Intervention |\n",
    "|----------|-------------|\n",
    "| 🥇 High | Agility training programs for UMKM |\n",
    "| 🥈 Medium | KUR (Kredit Usaha Rakyat) access expansion |\n",
    "| 🥉 Low | Digital literacy & e-commerce onboarding |\n",
    "\n",
    "### 🚀 Future Development\n",
    "\n",
    "- [ ] Deploy as **Streamlit** web application\n",
    "- [ ] Collect real survey data for model validation\n",
    "- [ ] Add longitudinal tracking of SME resilience over time\n",
    "- [ ] Implement Structural Equation Modelling (SEM) for causal inference\n",
    "- [ ] Expand to ASEAN-wide UMKM benchmarking\n",
    "\n",
    "---\n",
    "*© 2025 UMKM AI Research | Built with Python 3.12, Scikit-Learn, XGBoost, SHAP*\n",
))
cells.append(code(
    "# ── Final Project Summary ────────────────────────────────\n",
    "from pathlib import Path\n",
    "\n",
    "print('=' * 65)\n",
    "print('  🎉 UMKM AI PROJECT — EXECUTION COMPLETE')\n",
    "print('=' * 65)\n",
    "print(f'\\n  📁 Project Structure:')\n",
    "for d in ['data', 'model', 'figures']:\n",
    "    dir_path = PROJECT_ROOT / d\n",
    "    if dir_path.exists():\n",
    "        files = list(dir_path.iterdir())\n",
    "        print(f'     {d}/ — {len(files)} file(s)')\n",
    "        for f in files:\n",
    "            sz = f.stat().st_size / 1024\n",
    "            print(f'        • {f.name} ({sz:.1f} KB)')\n",
    "\n",
    "print(f'\\n  📊 Best Model       : {best_model_name}')\n",
    "print(f'  🎯 Test F1 Weighted : {comparison_df.iloc[0][\"F1 Weighted\"]:.4f}')\n",
    "print(f'  🧠 SHAP Top Feature : {shap_importance_df.iloc[0][\"Feature\"]}')\n",
    "print(f'  📦 Dataset          : 100 UMKM | 50 Variables | 3 Classes')\n",
    "print(f'\\n  ✅ All outputs successfully generated!')\n",
    "print('=' * 65)\n",
))

# ══════════════════════════════════════════════════════════════
# BUILD NOTEBOOK
# ══════════════════════════════════════════════════════════════
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.12.0"
        }
    },
    "cells": cells
}

output_path = os.path.join(NOTEBOOK_DIR, "UMKM_AI.ipynb")
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"✅ Notebook generated → {output_path}")
print(f"   Total cells: {len(cells)}")
